/**Fichier dans lequel définir l'ensemble des constantes
Ainsi, lors du versionnement du code, seul ce fichier est modifié lorsque l'on paufine les paramètres, ce qui limite les risques de modifications simultanées
d'un même fichier
*/

#ifndef CONSTANTES_H
#define CONSTANTES_H

#include <cmath>
/*
PARAMETRES GÉOMETRIQUES
*/
///Rayon des roues codeuses.
#define ROBOT_UNICYCLE_RAYON_GAUCHE                 3.0
#define ROBOT_UNICYCLE_RAYON_DROITE                 6.0
///Distance entre les roues codeuses
#define ROBOT_UNICYCLE_DISTANCE_ROUES               20.0

/*
PARAMETRES CINÉMATIQUES
*/
///Vitesse maximum d'avance (en unité de longueur par seconde)
#define ROBOT_UNICYCLE_VITESSE_AVANCER_MAX          100.0
///Vitesse minimum d'avance (en unité de longueur par seconde)
#define ROBOT_UNICYCLE_VITESSE_AVANCER_MIN          10.0
///Vitesse maximum de rotation (en tr/s)
#define ROBOT_UNICYCLE_VITESSE_ROTATION_MAX          0.1
///Vitesse minimum de rotation (en tr/s)
#define ROBOT_UNICYCLE_VITESSE_ROTATION_MIN          0.002
///Distance à laquelle la vitesse maximale est atteinte (pour Avancer)
#define ROBOT_UNICYCLE_DISTANCE_SEUIL_VITESSE_MAX   70.0
///Angle à partir duquel la vitesse angulaire maximale est atteinte (en rad, pour Tourner)
#define ROBOT_UNICYCLE_ANGLE_SEUIL_VITESSE_MAX      M_PI/180*10

/*
PARAMETRES DYNAMIQUES
*/
///Accélération maximale que supporte le robot en avançant (en unité de longueur par seconde^2)
///#define ROBOT_UNICYCLE_ACCELERATION_LINEAIRE_MAX    7000.0
///Accélération maximale que supporte le robot en tournant (en tr par seconde^2)
///#define ROBOT_UNICYCLE_ACCELERATION_ANGULAIRE_MAX    1.0

/*
PARAMÈTRES DE PRÉCISION
*/
///précision utilisée pour arrêter un ordre en distance.
#define ROBOT_UNICYCLE_PRECISION_DISTANCE           10.0
///précision utilisée pour arrêter un ordre en rotation.
#define ROBOT_UNICYCLE_PRECISION_ANGLE              M_PI/180*1

/*
PARAMÈTRES D'ASSERVISSEMENT
*/
///Période d'asservissement du côté PC
#define ROBOT_UNICYCLE_PERIODE_ASSERVISSEMENT       0.05

/*
CONSTANTES DÉDUITES
*/
#define ROBOT_UNICYCLE_PRECISION_DISTANCE_CARRE    ROBOT_UNICYCLE_PRECISION_DISTANCE*ROBOT_UNICYCLE_PRECISION_DISTANCE

#define ROBOT_UNICYCLE_VITESSE_ANGULAIRE_GAUCHE_AVANCER_MAX  ROBOT_UNICYCLE_VITESSE_AVANCER_MAX/ROBOT_UNICYCLE_RAYON_GAUCHE
#define ROBOT_UNICYCLE_VITESSE_ANGULAIRE_DROITE_AVANCER_MAX  ROBOT_UNICYCLE_VITESSE_AVANCER_MAX/ROBOT_UNICYCLE_RAYON_DROITE
#define ROBOT_UNICYCLE_VITESSE_ANGULAIRE_GAUCHE_AVANCER_MIN  ROBOT_UNICYCLE_VITESSE_AVANCER_MIN/ROBOT_UNICYCLE_RAYON_GAUCHE
#define ROBOT_UNICYCLE_VITESSE_ANGULAIRE_DROITE_AVANCER_MIN  ROBOT_UNICYCLE_VITESSE_AVANCER_MIN/ROBOT_UNICYCLE_RAYON_DROITE

#define ROBOT_UNICYCLE_VITESSE_LINEAIRE_ROTATION_MAX         ROBOT_UNICYCLE_VITESSE_ROTATION_MAX*2*M_PI*2*ROBOT_UNICYCLE_DISTANCE_ROUES
#define ROBOT_UNICYCLE_VITESSE_ANGULAIRE_GAUCHE_TOURNER_MAX  ROBOT_UNICYCLE_VITESSE_ROTATION_MAX*2*M_PI*2*ROBOT_UNICYCLE_DISTANCE_ROUES/ROBOT_UNICYCLE_RAYON_GAUCHE
#define ROBOT_UNICYCLE_VITESSE_ANGULAIRE_DROITE_TOURNER_MAX  ROBOT_UNICYCLE_VITESSE_ROTATION_MAX*2*M_PI*2*ROBOT_UNICYCLE_DISTANCE_ROUES/ROBOT_UNICYCLE_RAYON_DROITE
#define ROBOT_UNICYCLE_VITESSE_LINEAIRE_ROTATION_MIN         ROBOT_UNICYCLE_VITESSE_ROTATION_MIN*2*M_PI*2*ROBOT_UNICYCLE_DISTANCE_ROUES
#define ROBOT_UNICYCLE_VITESSE_ANGULAIRE_GAUCHE_TOURNER_MIN  ROBOT_UNICYCLE_VITESSE_ROTATION_MIN*2*M_PI*2*ROBOT_UNICYCLE_DISTANCE_ROUES/ROBOT_UNICYCLE_RAYON_GAUCHE
#define ROBOT_UNICYCLE_VITESSE_ANGULAIRE_DROITE_TOURNER_MIN  ROBOT_UNICYCLE_VITESSE_ROTATION_MIN*2*M_PI*2*ROBOT_UNICYCLE_DISTANCE_ROUES/ROBOT_UNICYCLE_RAYON_DROITE

#define ROBOT_UNICYCLE_TAUX_ACCROISSEMENT_VITESSE_MOTEUR_GAUCHE_AVANCER  (ROBOT_UNICYCLE_VITESSE_ANGULAIRE_GAUCHE_AVANCER_MAX-ROBOT_UNICYCLE_VITESSE_ANGULAIRE_GAUCHE_AVANCER_MIN)/ROBOT_UNICYCLE_DISTANCE_SEUIL_VITESSE_MAX
#define ROBOT_UNICYCLE_TAUX_ACCROISSEMENT_VITESSE_MOTEUR_DROITE_AVANCER  (ROBOT_UNICYCLE_VITESSE_ANGULAIRE_DROITE_AVANCER_MAX-ROBOT_UNICYCLE_VITESSE_ANGULAIRE_DROITE_AVANCER_MIN)/ROBOT_UNICYCLE_DISTANCE_SEUIL_VITESSE_MAX

#define ROBOT_UNICYCLE_TAUX_ACCROISSEMENT_VITESSE_MOTEUR_GAUCHE_TOURNER  (ROBOT_UNICYCLE_VITESSE_ANGULAIRE_GAUCHE_TOURNER_MAX-ROBOT_UNICYCLE_VITESSE_ANGULAIRE_GAUCHE_TOURNER_MIN)/ROBOT_UNICYCLE_ANGLE_SEUIL_VITESSE_MAX
#define ROBOT_UNICYCLE_TAUX_ACCROISSEMENT_VITESSE_MOTEUR_DROITE_TOURNER  (ROBOT_UNICYCLE_VITESSE_ANGULAIRE_DROITE_TOURNER_MAX-ROBOT_UNICYCLE_VITESSE_ANGULAIRE_DROITE_TOURNER_MIN)/ROBOT_UNICYCLE_ANGLE_SEUIL_VITESSE_MAX

///Distance de la cible à partir de laquel il faut commencer à ralentir
//#define ROBOT_UNICYCLE_DISTANCE_SEUIL_VITESSE_MAX           ((ROBOT_UNICYCLE_VITESSE_AVANCER_MAX-ROBOT_UNICYCLE_VITESSE_AVANCER_MIN)*(ROBOT_UNICYCLE_VITESSE_AVANCER_MAX-ROBOT_UNICYCLE_VITESSE_AVANCER_MIN)/(2*ROBOT_UNICYCLE_ACCELERATION_LINEAIRE_MAX)+ROBOT_UNICYCLE_VITESSE_AVANCER_MIN*(ROBOT_UNICYCLE_VITESSE_AVANCER_MAX-ROBOT_UNICYCLE_VITESSE_AVANCER_MIN)/ROBOT_UNICYCLE_ACCELERATION_LINEAIRE_MAX)

#endif
